_END=\033[0m
_BOLD=\033[1m
_UNDER=\033[4m
_REV=\033[7m

_RED=\033[31m
_GREEN=\033[32m
_YELLOW=\033[33m
_BLUE=\033[34m
_PURPLE=\033[35m
_CYAN=\033[36m
_WHITE=\033[37m

_IGREY=\033[40m
_IRED=\033[41m
_IGREEN=\033[42m
_IYELLOW=\033[43m
_IBLUE=\033[44m
_IPURPLE=\033[45m
_ICYAN=\033[46m
_IWHITE=\033[47m

NAME = libft.a

CC = clang
CFLAGS = -Wall -Wextra -Werror
# CFLAGS += $(CDEFFLAGS) -O3 -fno-builtin
CFLAGS += $(CDEFFLAGS) -g
# CFLAGS += $(CDEFFLAGS) -fsanitize=address

MAKE = make --no-print-directory

HEADER = libft.h

OBJS = $(SRCS:%.c=%.o)
SRCS = \
	src/ft_atoi.c \
	src/ft_is_p1.c \
	src/ft_is_p2.c \
	src/ft_print_err.c \
	src/ft_strlen.c \
	src/ft_lstadd.c \
	src/ft_lstnew.c \
	src/ft_get_next_line.c \
	src/ft_strdup.c \
	src/ft_strcmp.c \
	src/push.c \
	src/rot.c \
	src/rrot.c \
	src/swap.c \
	src/is_sorted.c \
	src/print_stacks.c \
	src/ft_putstr_fd.c \
	src/close.c \

%.o: %.c $(HEADER)
	@printf "[ ${_PURPLE}${_BOLD}${NAME}${_END} ] > [ $(_GREEN)$(_BOLD)+$(_END) ][ compiling ] $(_BLUE)$(_BOLD)$<$(_END)\n"
	@$(CC) $(CFLAGS) -c $< -o $@

all: ${NAME}

$(NAME): $(OBJS)
	@printf "[ ${_PURPLE}${_BOLD}${NAME}${_END} ] > [ $(_GREEN)$(_BOLD)+$(_END) ][ building ] $(_BLUE)$(_BOLD)$(NAME)$(_END)\n"
	@$(AR) rcs $(NAME) $(OBJS)
	@printf "[ ${_PURPLE}${_BOLD}${NAME}${_END} ] > [ $(_BLUE)$(_BOLD)!$(_END) ][ done ]\n"

re: fclean
	@$(MAKE) all

clean:
	@$(RM) $(OBJS)
	@printf "[ ${_PURPLE}${_BOLD}${NAME}${_END} ] > [ $(_RED)$(_BOLD)-$(_END) ][ removing ] $(_BLUE)$(_BOLD)objs $(_END)\n"

fclean: clean
	@$(RM) $(NAME)
	@printf "[ ${_PURPLE}${_BOLD}${NAME}${_END} ] > [ $(_RED)$(_BOLD)-$(_END) ][ removing ] $(_BLUE)$(_BOLD)$(NAME) $(_END)\n"

norm:
	@norminettev2

.PHONY: all re clean fclean norm